import { Puzzles } from "../../Puzzles/Puzzles";
import { Themes } from "../../Themes";
import { AreaConfig } from "../Area";

export const area: AreaConfig = {
  name: "Space",
  theme: Themes.Space,
  unlock_level: {
    hint: <>Unlock this area</>,
    isUnlockLevel: true,
    level: {
      gameCategory: "wingo",
      levelProps: {
        mode: "repeat",
        targetWord: "space",
        enforceFullLengthGuesses: true,
        defaultWordLength: 5,
        defaultnumGuesses: 6,
        keyboard: true,
        firstLetterProvided: false,
        checkInDictionary: false,
        puzzleLeaveNumBlanks: 0,
        puzzleRevealMs: 0,
        timerConfig: { isTimed: false },
      },
    },
  },

  levels: [
    {
      hint: <>Only known inhabitted planet</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "earth",
          enforceFullLengthGuesses: true,
          defaultWordLength: 5,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet of men</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "mars",
          enforceFullLengthGuesses: true,
          defaultWordLength: 4,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Path followed around a bigger object</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "orbit",
          enforceFullLengthGuesses: true,
          defaultWordLength: 5,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet of women</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "venus",
          enforceFullLengthGuesses: true,
          defaultWordLength: 5,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet sharing a name with a metal</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "mercury",
          enforceFullLengthGuesses: true,
          defaultWordLength: 7,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Attractive force</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "gravity",
          enforceFullLengthGuesses: true,
          defaultWordLength: 7,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 4,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet with a storm greater in size than the earth</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "jupiter",
          enforceFullLengthGuesses: true,
          defaultWordLength: 7,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Gravitationally bound collection of stars</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "galaxy",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet of the sea</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "neptune",
          enforceFullLengthGuesses: true,
          defaultWordLength: 7,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Outburst of energy from a star</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "flare",
          enforceFullLengthGuesses: true,
          defaultWordLength: 5,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: null,
      level: {
        gameCategory: "puzzle",
        levelProps: {
          ...Puzzles.Easy1IconHorizontallyAcrross,
        },
      },
    },
    {
      hint: <>Planet with icy rings</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "saturn",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Radient emission</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "aurora",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet that spins on its side</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "uranus",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
  ],
};
