import { Themes } from "../../Themes";
import { AreaConfig } from "../Area";

export const area: AreaConfig = {
  name: "Travel",
  theme: Themes.Travel,
  unlock_level: {
    hint: <>Unlock this area</>,
    isUnlockLevel: true,
    level: {
      gameCategory: "wingo",
      levelProps: {
        mode: "repeat",
        targetWord: "travel",
        enforceFullLengthGuesses: true,
        defaultWordLength: 6,
        defaultnumGuesses: 6,
        keyboard: true,
        firstLetterProvided: true,
        checkInDictionary: false,
        puzzleLeaveNumBlanks: 0,
        puzzleRevealMs: 0,
        timerConfig: { isTimed: false },
      },
    },
  },

  levels: [
    {
      hint: <>Gravitationally bound collection of stars</>,
      levelButtonCoords: {
        x: 14,
        y: 27,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "galaxy",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet of the sea</>,
      levelButtonCoords: {
        x: 18,
        y: 30,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "neptune",
          enforceFullLengthGuesses: true,
          defaultWordLength: 7,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Outburst of energy from a star</>,
      levelButtonCoords: {
        x: 22,
        y: 28,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "flare",
          enforceFullLengthGuesses: true,
          defaultWordLength: 5,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet with icy rings</>,
      levelButtonCoords: {
        x: 26,
        y: 24,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "saturn",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Radient emission</>,
      levelButtonCoords: {
        x: 30,
        y: 26,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "aurora",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Planet that spins on its side</>,
      levelButtonCoords: {
        x: 28,
        y: 36,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "uranus",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 6,
          keyboard: true,
          firstLetterProvided: false,
          puzzleLeaveNumBlanks: 0,
          puzzleRevealMs: 0,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 24,
        y: 38,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 19,
        y: 39,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 17,
        y: 47,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 17,
        y: 55,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 20,
        y: 62,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 23,
        y: 68,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 29,
        y: 68,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 34,
        y: 74,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 31,
        y: 77,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 26,
        y: 84,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
    {
      hint: <>Super heated gas</>,
      levelButtonCoords: {
        x: 25,
        y: 94,
      },
      level: {
        gameCategory: "wingo",
        levelProps: {
          mode: "repeat",
          targetWord: "plasma",
          enforceFullLengthGuesses: true,
          defaultWordLength: 6,
          defaultnumGuesses: 7,
          keyboard: true,
          firstLetterProvided: true,
          puzzleLeaveNumBlanks: 3,
          puzzleRevealMs: 1500,
          timerConfig: { isTimed: false },
        },
      },
    },
  ],
};
