// TODO: Manually enter adjacent pins for the different grid sizes (and shapes?)

export const adjacentMappings_25 = [
    { pin: 1, adjacent_pins: [2, 3] },
    { pin: 2, adjacent_pins: [1, 3, 4, 5] },
    { pin: 3, adjacent_pins: [] },
    { pin: 4, adjacent_pins: [] },
    { pin: 5, adjacent_pins: [] },
    { pin: 6, adjacent_pins: [] },
    { pin: 7, adjacent_pins: [] },
    { pin: 8, adjacent_pins: [] },
    { pin: 9, adjacent_pins: [] },
    { pin: 10, adjacent_pins: [] },
    { pin: 11, adjacent_pins: [] },
    { pin: 12, adjacent_pins: [] },
    { pin: 13, adjacent_pins: [] },
    { pin: 14, adjacent_pins: [] },
    { pin: 15, adjacent_pins: [] },
    { pin: 16, adjacent_pins: [] },
    { pin: 17, adjacent_pins: [] },
    { pin: 18, adjacent_pins: [] },
    { pin: 19, adjacent_pins: [] },
    { pin: 20, adjacent_pins: [] },
    { pin: 21, adjacent_pins: [] },
    { pin: 22, adjacent_pins: [] },
    { pin: 23, adjacent_pins: [] },
    { pin: 24, adjacent_pins: [] },
    { pin: 25, adjacent_pins: [] },
  ];

  export const adjacentMappings_64 = [
    { pin: 1, adjacent_pins: [2, 3] },
    { pin: 2, adjacent_pins: [1, 3, 4, 5] },
    { pin: 3, adjacent_pins: [] },
    { pin: 4, adjacent_pins: [] },
    { pin: 5, adjacent_pins: [] },
    { pin: 6, adjacent_pins: [] },
    { pin: 7, adjacent_pins: [] },
    { pin: 8, adjacent_pins: [] },
    { pin: 9, adjacent_pins: [] },
    { pin: 10, adjacent_pins: [] },
    { pin: 11, adjacent_pins: [] },
    { pin: 12, adjacent_pins: [] },
    { pin: 13, adjacent_pins: [] },
    { pin: 14, adjacent_pins: [] },
    { pin: 15, adjacent_pins: [] },
    { pin: 16, adjacent_pins: [] },
    { pin: 17, adjacent_pins: [] },
    { pin: 18, adjacent_pins: [] },
    { pin: 19, adjacent_pins: [] },
    { pin: 20, adjacent_pins: [] },
    { pin: 21, adjacent_pins: [] },
    { pin: 22, adjacent_pins: [] },
    { pin: 23, adjacent_pins: [] },
    { pin: 24, adjacent_pins: [] },
    { pin: 25, adjacent_pins: [] },
  ];

  export const adjacentMappings_100 = [
    { pin: 1, adjacent_pins: [2, 3] },
    { pin: 2, adjacent_pins: [1, 3, 4, 5] },
    { pin: 3, adjacent_pins: [] },
    { pin: 4, adjacent_pins: [] },
    { pin: 5, adjacent_pins: [] },
    { pin: 6, adjacent_pins: [] },
    { pin: 7, adjacent_pins: [] },
    { pin: 8, adjacent_pins: [] },
    { pin: 9, adjacent_pins: [] },
    { pin: 10, adjacent_pins: [] },
    { pin: 11, adjacent_pins: [] },
    { pin: 12, adjacent_pins: [] },
    { pin: 13, adjacent_pins: [] },
    { pin: 14, adjacent_pins: [] },
    { pin: 15, adjacent_pins: [] },
    { pin: 16, adjacent_pins: [] },
    { pin: 17, adjacent_pins: [] },
    { pin: 18, adjacent_pins: [] },
    { pin: 19, adjacent_pins: [] },
    { pin: 20, adjacent_pins: [] },
    { pin: 21, adjacent_pins: [] },
    { pin: 22, adjacent_pins: [] },
    { pin: 23, adjacent_pins: [] },
    { pin: 24, adjacent_pins: [] },
    { pin: 25, adjacent_pins: [] },
  ];