// TODO: https://www.worlddata.info/capital-cities.php#europa

export const capital_cities = [
  { countryName: "Åland Islands", capitalName: "Mariehamn" },
  { countryName: "Albania", capitalName: "Tirana" },
  { countryName: "Andorra", capitalName: "Andorra la Vella" },
  { countryName: "Austria", capitalName: "Vienna" },
  { countryName: "Belarus", capitalName: "Minsk" },
  { countryName: "Belgium", capitalName: "Brussels" },
  { countryName: "Bosnia and Herzegovina", capitalName: "Sarajevo" },
  { countryName: "Bulgaria", capitalName: "Sofia" },
  { countryName: "Croatia", capitalName: "Zagreb" },
  { countryName: "Czechia", capitalName: "Prague" },
  { countryName: "Denmark", capitalName: "Copenhagen" },
  { countryName: "Estonia", capitalName: "Tallinn" },
  { countryName: "Faroe Islands", capitalName: "Tórshavn" },
  { countryName: "Finland", capitalName: "Helsinki" },
  { countryName: "France", capitalName: "Paris" },
  { countryName: "Germany", capitalName: "Berlin" },
  { countryName: "Gibraltar", capitalName: "Gibraltar" },
  { countryName: "Greece", capitalName: "Athens" },
  { countryName: "Guernsey", capitalName: "Saint Peter Port" },
  { countryName: "Hungary", capitalName: "Budapest" },
  { countryName: "Iceland", capitalName: "Reykjavík" },
  { countryName: "Ireland", capitalName: "Dublin" },
  { countryName: "Isle of Man", capitalName: "Douglas" },
  { countryName: "Italy", capitalName: "Rome" },
  { countryName: "Jersey", capitalName: "Saint Helier" },
  { countryName: "Kosovo", capitalName: "Pristina" },
  { countryName: "Latvia", capitalName: "Riga" },
  { countryName: "Liechtenstein", capitalName: "Vaduz" },
  { countryName: "Lithuania", capitalName: "Vilnius" },
  { countryName: "Luxembourg", capitalName: "Luxembourg" },
  { countryName: "Malta", capitalName: "Valletta" },
  { countryName: "Moldova", capitalName: "Chisinau" },
  { countryName: "Montenegro", capitalName: "Podgorica" },
  { countryName: "Netherlands", capitalName: "Amsterdam" },
  { countryName: "North Macedonia", capitalName: "Skopje" },
  { countryName: "Norway", capitalName: "Oslo" },
  { countryName: "Poland", capitalName: "Warsaw" },
  { countryName: "Portugal", capitalName: "Lisbon" },
  { countryName: "Principality of Monaco", capitalName: "Monaco" },
  { countryName: "Romania", capitalName: "Bucharest" },
  { countryName: "Russia", capitalName: "Moscow" },
  { countryName: "San Marino", capitalName: "San Marino" },
  { countryName: "Serbia", capitalName: "Belgrade" },
  { countryName: "Slovakia", capitalName: "Bratislava" },
  { countryName: "Slovenia", capitalName: "Ljubljana" },
  { countryName: "Spain", capitalName: "Madrid" },
  { countryName: "Svalbard", capitalName: "Longyearbyen" },
  { countryName: "Sweden", capitalName: "Stockholm" },
  { countryName: "Switzerland", capitalName: "Bern" },
  { countryName: "Ukraine", capitalName: "Kiev" },
  { countryName: "United Kingdom", capitalName: "London" },
  { countryName: "Vatican City", capitalName: "Città del Vaticano" },
  { countryName: "Anguilla", capitalName: "The Valley" },
  { countryName: "Antigua and Barbuda", capitalName: "Saint Johns" },
  { countryName: "Argentina", capitalName: "Buenos Aires" },
  { countryName: "Aruba", capitalName: "Oranjestad" },
  { countryName: "Bahamas", capitalName: "Nassau" },
  { countryName: "Barbados", capitalName: "Bridgetown" },
  { countryName: "Belize", capitalName: "Belmopan" },
  { countryName: "Bermuda", capitalName: "Hamilton" },
  { countryName: "Bolivia", capitalName: "Sucre" },
  { countryName: "Brazil", capitalName: "Brasília" },
  { countryName: "British Virgin Islands", capitalName: "Road Town" },
  { countryName: "Canada", capitalName: "Ottawa" },
  { countryName: "Cayman Islands", capitalName: "George Town" },
  { countryName: "Chile", capitalName: "Santiago" },
  { countryName: "Colombia", capitalName: "Bogotá" },
  { countryName: "Costa Rica", capitalName: "San José" },
  { countryName: "Cuba", capitalName: "Havana" },
  { countryName: "Curacao", capitalName: "Willemstad" },
  { countryName: "Dominica", capitalName: "Roseau" },
  { countryName: "Dominican Republic", capitalName: "Santo Domingo" },
  { countryName: "Ecuador", capitalName: "Quito" },
  { countryName: "El Salvador", capitalName: "San Salvador" },
  { countryName: "Falkland Islands", capitalName: "Stanley" },
  { countryName: "French Guiana", capitalName: "Cayenne" },
  { countryName: "Greenland", capitalName: "Nuuk" },
  { countryName: "Grenada", capitalName: "Saint George's" },
  { countryName: "Guadeloupe", capitalName: "Basse-Terre" },
  { countryName: "Guatemala", capitalName: "Guatemala City" },
  { countryName: "Guyana", capitalName: "Georgetown" },
  { countryName: "Haiti", capitalName: "Port-au-Prince" },
  { countryName: "Honduras", capitalName: "Tegucigalpa" },
  { countryName: "Jamaica", capitalName: "Kingston" },
  { countryName: "Martinique", capitalName: "Fort-de-France" },
  { countryName: "Mexico", capitalName: "Mexico City" },
  { countryName: "Montserrat", capitalName: "Brades" },
  { countryName: "Nicaragua", capitalName: "Managua" },
  { countryName: "Panama", capitalName: "Panama City" },
  { countryName: "Paraguay", capitalName: "Asunción" },
  { countryName: "Peru", capitalName: "Lima" },
  { countryName: "Puerto Rico", capitalName: "San Juan" },
  { countryName: "Saint Barthelemy", capitalName: "Gustavia" },
  { countryName: "Saint Kitts and Nevis", capitalName: "Basseterre" },
  { countryName: "Saint Lucia", capitalName: "Castries" },
  { countryName: "Saint Martin", capitalName: "Marigot" },
  { countryName: "Saint Pierre and Miquelon", capitalName: "Saint-Pierre" },
  {
    countryName: "Saint Vincent and the Grenadines",
    capitalName: "Kingstown",
  },
  { countryName: "Sint Maarten", capitalName: "Philipsburg" },
  {
    countryName: "South Georgia and South Sandwich Islands",
    capitalName: "King Edward Point",
  },
  { countryName: "Suriname", capitalName: "Paramaribo" },
  { countryName: "Trinidad and Tobago", capitalName: "Port-of-Spain" },
  { countryName: "Turks and Caicos Islands", capitalName: "Cockburn Town" },
  { countryName: "United States", capitalName: "Washington, D.C." },
  { countryName: "Uruguay", capitalName: "Montevideo" },
  { countryName: "Venezuela", capitalName: "Caracas" },
  { countryName: "Virgin Islands", capitalName: "Charlotte Amalie" },
  { countryName: "Afghanistan", capitalName: "Kabul" },
  { countryName: "Armenia", capitalName: "Yerevan" },
  { countryName: "Azerbaijan", capitalName: "Baku" },
  { countryName: "Bahrain", capitalName: "Manama" },
  { countryName: "Bangladesh", capitalName: "Dhaka" },
  { countryName: "Bhutan", capitalName: "Thimphu" },
  { countryName: "Brunei", capitalName: "Bandar Seri Begawan" },
  { countryName: "Burma", capitalName: "Nay Pyi Taw" },
  { countryName: "Cambodia", capitalName: "Phnom Penh" },
  { countryName: "China", capitalName: "Beijing" },
  { countryName: "Cyprus", capitalName: "Nicosia" },
  { countryName: "East Timor", capitalName: "Dili" },
  { countryName: "Georgia", capitalName: "Tbilisi" },
  { countryName: "Hong Kong", capitalName: "Hong Kong" },
  { countryName: "India", capitalName: "New Delhi" },
  { countryName: "Indonesia", capitalName: "Jakarta" },
  { countryName: "Iran", capitalName: "Tehran" },
  { countryName: "Iraq", capitalName: "Baghdad" },
  { countryName: "Israel", capitalName: "Jerusalem" },
  { countryName: "Japan", capitalName: "Tokyo" },
  { countryName: "Jordan", capitalName: "Amman" },
  { countryName: "Kazakhstan", capitalName: "Nursultan" },
  { countryName: "Kuwait", capitalName: "Kuwait City" },
  { countryName: "Kyrgyzstan", capitalName: "Bishkek" },
  { countryName: "Laos", capitalName: "Vientiane" },
  { countryName: "Lebanon", capitalName: "Beirut" },
  { countryName: "Macao", capitalName: "Concelho de Macau" },
  { countryName: "Malaysia", capitalName: "Kuala Lumpur" },
  { countryName: "Maldives", capitalName: "Malé" },
  { countryName: "Mongolia", capitalName: "Ulaanbaatar" },
  { countryName: "Nepal", capitalName: "Kathmandu" },
  { countryName: "North Korea", capitalName: "Pyongyang" },
  { countryName: "Oman", capitalName: "Muscat" },
  { countryName: "Pakistan", capitalName: "Islamabad" },
  { countryName: "Palestine", capitalName: "Ramallah" },
  { countryName: "Philippines", capitalName: "Manila" },
  { countryName: "Qatar", capitalName: "Doha" },
  { countryName: "Saudi Arabia", capitalName: "Riyadh" },
  { countryName: "Singapore", capitalName: "Singapore" },
  { countryName: "South Korea", capitalName: "Seoul" },
  { countryName: "Sri Lanka", capitalName: "Colombo" },
  { countryName: "Syria", capitalName: "Damascus" },
  { countryName: "Taiwan", capitalName: "Taipei" },
  { countryName: "Tajikistan", capitalName: "Dushanbe" },
  { countryName: "Thailand", capitalName: "Bangkok" },
  { countryName: "Turkey", capitalName: "Ankara" },
  { countryName: "Turkmenistan", capitalName: "Ashgabat" },
  { countryName: "United Arab Emirates", capitalName: "Abu Dhabi" },
  { countryName: "Uzbekistan", capitalName: "Tashkent" },
  { countryName: "Vietnam", capitalName: "Hanoi" },
  { countryName: "Yemen", capitalName: "Sanaa" },
  { countryName: "Australia", capitalName: "Canberra" },
  { countryName: "Christmas Island", capitalName: "Flying Fish Cove" },
  { countryName: "Cocos (Keeling) Islands", capitalName: "West Island" },
  { countryName: "New Zealand", capitalName: "Wellington" },
  { countryName: "Norfolk Island", capitalName: "Kingston" },
  { countryName: "Algeria", capitalName: "Algiers" },
  { countryName: "Angola", capitalName: "Luanda" },
  { countryName: "Benin", capitalName: "Porto-Novo" },
  { countryName: "Botswana", capitalName: "Gaborone" },
  { countryName: "Burkina Faso", capitalName: "Ouagadougou" },
  { countryName: "Burundi", capitalName: "Bujumbura" },
  { countryName: "Cameroon", capitalName: "Yaoundé" },
  { countryName: "Cape Verde", capitalName: "Praia" },
  { countryName: "Central African Republic", capitalName: "Bangui" },
  { countryName: "Chad", capitalName: "N'Djamena" },
  { countryName: "Comoros", capitalName: "Moroni" },
  {
    countryName: "Democratic Republic of the Congo",
    capitalName: "Kinshasa",
  },
  { countryName: "Djibouti", capitalName: "Djibouti" },
  { countryName: "Egypt", capitalName: "Cairo" },
  { countryName: "Equatorial Guinea", capitalName: "Malabo" },
  { countryName: "Eritrea", capitalName: "Asmara" },
  { countryName: "Eswatini", capitalName: "Mbabane" },
  { countryName: "Ethiopia", capitalName: "Addis Ababa" },
  { countryName: "Gabon", capitalName: "Libreville" },
  { countryName: "Gambia", capitalName: "Banjul" },
  { countryName: "Ghana", capitalName: "Accra" },
  { countryName: "Guinea", capitalName: "Conakry" },
  { countryName: "Guinea-Bissau", capitalName: "Bissau" },
  { countryName: "Ivory Coast", capitalName: "Yamoussoukro" },
  { countryName: "Kenya", capitalName: "Nairobi" },
  { countryName: "Lesotho", capitalName: "Maseru" },
  { countryName: "Liberia", capitalName: "Monrovia" },
  { countryName: "Libya", capitalName: "Tripoli" },
  { countryName: "Madagascar", capitalName: "Antananarivo" },
  { countryName: "Malawi", capitalName: "Lilongwe" },
  { countryName: "Mali", capitalName: "Bamako" },
  { countryName: "Mauritania", capitalName: "Nouakchott" },
  { countryName: "Mauritius", capitalName: "Port Louis" },
  { countryName: "Mayotte", capitalName: "Mamoudzou" },
  { countryName: "Morocco", capitalName: "Rabat" },
  { countryName: "Mozambique", capitalName: "Maputo" },
  { countryName: "Namibia", capitalName: "Windhoek" },
  { countryName: "Niger", capitalName: "Niamey" },
  { countryName: "Nigeria", capitalName: "Abuja" },
  { countryName: "Republic of the Congo", capitalName: "Brazzaville" },
  { countryName: "Reunion", capitalName: "Saint-Denis" },
  { countryName: "Rwanda", capitalName: "Kigali" },
  {
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    capitalName: "Jamestown",
  },
  { countryName: "Sao Tome and Principe", capitalName: "São Tomé" },
  { countryName: "Senegal", capitalName: "Dakar" },
  { countryName: "Seychelles", capitalName: "Victoria" },
  { countryName: "Sierra Leone", capitalName: "Freetown" },
  { countryName: "Somalia", capitalName: "Mogadishu" },
  { countryName: "South Africa", capitalName: "Pretoria" },
  { countryName: "South Sudan", capitalName: "Juba" },
  { countryName: "Sudan", capitalName: "Khartoum" },
  { countryName: "Tanzania", capitalName: "Dodoma" },
  { countryName: "Togo", capitalName: "Lomé" },
  { countryName: "Tunisia", capitalName: "Tunis" },
  { countryName: "Uganda", capitalName: "Kampala" },
  { countryName: "Western Sahara", capitalName: "El Aaiún" },
  { countryName: "Zambia", capitalName: "Lusaka" },
  { countryName: "Zimbabwe", capitalName: "Harare" },
  { countryName: "American Samoa", capitalName: "Pago Pago" },
  { countryName: "Cook Islands", capitalName: "Avarua" },
  { countryName: "Fiji", capitalName: "Suva" },
  { countryName: "French Polynesia", capitalName: "Papeete" },
  { countryName: "Guam", capitalName: "Hagåtña" },
  { countryName: "Kiribati", capitalName: "Tarawa" },
  { countryName: "Marshall Islands", capitalName: "Majuro" },
  { countryName: "Nauru", capitalName: "Yaren" },
  { countryName: "New Caledonia", capitalName: "Nouméa" },
  { countryName: "Niue", capitalName: "Alofi" },
  { countryName: "Northern Mariana Islands", capitalName: "Saipan" },
  { countryName: "Papua New Guinea", capitalName: "Port Moresby" },
  { countryName: "Pitcairn Islands", capitalName: "Adamstown" },
  { countryName: "Samoa", capitalName: "Apia" },
  { countryName: "Solomon Islands", capitalName: "Honiara" },
  { countryName: "Tonga", capitalName: "Nukualofa" },
  { countryName: "Tuvalu", capitalName: "Funafuti" },
  { countryName: "Vanuatu", capitalName: "Port-Vila" },
  { countryName: "Wallis and Futuna", capitalName: "Mata-Utu" },
];
