// https://simple.wikipedia.org/wiki/List_of_colors

export const words_colours = [
  { word: "amaranth", hint: "" },
  { word: "amber", hint: "Yellowish, also a gem" },
  { word: "amethyst", hint: "" },
  { word: "apricot", hint: "Orangish, also a fruit" },
  { word: "aquamarine", hint: "" },
  { word: "azure", hint: "" },
  { word: "baby-blue", hint: "" },
  { word: "beige", hint: "" },
  { word: "black", hint: "" },
  { word: "blue", hint: "" },
  { word: "blush", hint: "" },
  { word: "bronze", hint: "" },
  { word: "brown", hint: "" },
  { word: "burgundy", hint: "" },
  { word: "byzantium", hint: "" },
  { word: "carmine", hint: "" },
  { word: "cerise", hint: "" },
  { word: "cerulean", hint: "" },
  { word: "champagne", hint: "Pale, also a drink" },
  { word: "chocolate", hint: "Brownish, also a food" },
  { word: "coffee", hint: "Dark brown, also a drink" },
  { word: "copper", hint: "Brownish, also a metal" },
  { word: "coral", hint: "" },
  { word: "crimson", hint: "Blood colour" },
  { word: "cyan", hint: "" },
  { word: "emerald", hint: "Greenish, also a gem" },
  { word: "erin", hint: "" },
  { word: "gold", hint: "Yellowish, also a metal" },
  { word: "gray", hint: "" },
  { word: "green", hint: "" },
  { word: "harlequin", hint: "" },
  { word: "indigo", hint: "" },
  { word: "ivory", hint: "Whiteish, also a material" },
  { word: "jade", hint: "Greeenish, also a gem" },
  { word: "lavender", hint: "Purple, also a plant" },
  { word: "lemon", hint: "Yellowish, also a fruit" },
  { word: "lilac", hint: "" },
  { word: "lime", hint: "Greenish, also a fruit" },
  { word: "magenta", hint: "" },
  { word: "maroon", hint: "" },
  { word: "mauve", hint: "" },
  { word: "navy-blue", hint: "" },
  { word: "ochre", hint: "" },
  { word: "olive", hint: "Greenish, also a shrub" },
  { word: "orange", hint: "" },
  { word: "orchid", hint: "Pink, also a plant" },
  { word: "peach", hint: "" },
  { word: "pear", hint: "Green, also a fruit" },
  { word: "pink", hint: "" },
  { word: "plum", hint: "Purple, also a fruit" },
  { word: "puce", hint: "" },
  { word: "purple", hint: "" },
  { word: "raspberry", hint: "Redish, also a fruit" },
  { word: "red", hint: "" },
  { word: "rose", hint: "Pink, also a flower" },
  { word: "ruby", hint: "Redish, also a gem" },
  { word: "salmon", hint: "Pinkish, also a fish" },
  { word: "sangria", hint: "Redish orange, also a drink" },
  { word: "sapphire", hint: "Blueish, also a gem" },
  { word: "scarlet", hint: "Dark red, also a disease" },
  { word: "silver", hint: "Greyish, also a metal" },
  { word: "tan", hint: "" },
  { word: "taupe", hint: "" },
  { word: "teal", hint: "" },
  { word: "turquoise", hint: "" },
  { word: "violet", hint: "" },
  { word: "white", hint: "Lightest of all colours" },
  { word: "yellow", hint: "" },
];
