// https://simple.wikipedia.org/wiki/List_of_colors

export const words_colours = [
  { word: "amber", hint: "Yellowish, also a gemstone" },
  { word: "amethyst", hint: "Purplish, also a gemstone" },
  { word: "apricot", hint: "Orangish, also a fruit" },
  { word: "azure", hint: "Blueish" },
  { word: "beige", hint: "Brownish" },
  { word: "black", hint: "Darkest of all colours" },
  { word: "blue", hint: "One of the primary colours" },
  { word: "bronze", hint: "Brownish, also a metal" },
  { word: "brown", hint: "" },
  { word: "burgundy", hint: "Purplish" },
  { word: "cerise", hint: "Deep redish pink" },
  { word: "cerulean", hint: "" },
  { word: "champagne", hint: "Pale, also a drink" },
  { word: "chocolate", hint: "Brownish, also a food" },
  { word: "coffee", hint: "Dark brown, also a drink" },
  { word: "copper", hint: "Brownish, also a metal" },
  { word: "coral", hint: "Redish, also a marine invertebrate" },
  { word: "crimson", hint: "Blood colour" },
  { word: "cyan", hint: "Light blue" },
  { word: "emerald", hint: "Greenish, also a gemstone" },
  { word: "gold", hint: "Yellowish, also a metal" },
  { word: "gray", hint: "Between white and black" },
  { word: "green", hint: "Combination of yellow and blue" },
  { word: "indigo", hint: "Vivid blue" },
  { word: "ivory", hint: "Whiteish, also a material" },
  { word: "jade", hint: "Greeenish, also a gemstone" },
  { word: "lavender", hint: "Purple, also a plant" },
  { word: "lemon", hint: "Yellowish, also a fruit" },
  { word: "lilac", hint: "" },
  { word: "lime", hint: "Greenish, also a fruit" },
  { word: "magenta", hint: "Between red and blue in RGB colour" },
  { word: "maroon", hint: "" },
  { word: "mauve", hint: "" },
  { word: "ochre", hint: "" },
  { word: "olive", hint: "Greenish, also a shrub" },
  { word: "orange", hint: "Combination of red and yellow" },
  { word: "orchid", hint: "Pink, also a plant" },
  { word: "peach", hint: "" },
  { word: "pear", hint: "Green, also a fruit" },
  { word: "pink", hint: "" },
  { word: "plum", hint: "Purple, also a fruit" },
  { word: "puce", hint: "" },
  { word: "purple", hint: "Combination of red and blue" },
  { word: "raspberry", hint: "Redish, also a fruit" },
  { word: "red", hint: "One of the primary colours" },
  { word: "rose", hint: "Pink, also a flower" },
  { word: "ruby", hint: "Redish, also a gemstone" },
  { word: "salmon", hint: "Pinkish, also a fish" },
  { word: "sangria", hint: "Redish orange, also a drink" },
  { word: "sapphire", hint: "Blueish, also a gemstone" },
  { word: "scarlet", hint: "Dark red, also a disease" },
  { word: "silver", hint: "Greyish, also a metal" },
  { word: "tan", hint: "" },
  { word: "taupe", hint: "" },
  { word: "teal", hint: "" },
  { word: "turquoise", hint: "" },
  { word: "violet", hint: "" },
  { word: "white", hint: "Lightest of all colours" },
  { word: "yellow", hint: "One of the primary colours" },
];
