export const wordHintMappings = [
    { word: "acceptance", hint: "Be kind and understanding with this answer" },
    { word: "adrenaline", hint: "Fight or Flight" },
    { word: "accountant", hint: "This answer takes charge of company finances" },
    { word: "ammunition", hint: "A gun uses this answer" },
    { word: "aftershock", hint: "A smaller earthquake that follows a larger earthquake" },
    { word: "adjustment", hint: "A slight change is in order with this answer" },
    { word: "allocation", hint: "Giving out parts of a whole" },
    { word: "ambassador", hint: "This person is a high-ranking diplomat" },
    { word: "appearance", hint: "Check this answer in the mirror" },
    { word: "arithmetic", hint: "This answer is all about addition, subtraction, multiplication and division" },
    { word: "assessment", hint: "This answer is being tested" },
    { word: "assistance", hint: "This answer needs some help" },
    { word: "assumption", hint: "This answer made a judgement with no proof" },
    { word: "atmosphere", hint: "The layer before space" },
    { word: "attachment", hint: "Including something else with an email" },
    { word: "attraction", hint: "Love at first sight with this answer" },
    { word: "background", hint: "Setting the scene for the forefront" },
    { word: "bankruptcy", hint: "This answer has no money" },
    { word: "basketball", hint: "Slam dunk" },
    { word: "bestseller", hint: "The most popular of books" },
    { word: "binoculars", hint: "This answer helps with viewing distant objects" },
    { word: "breadcrumb", hint: "Very small piece of a loaf" },
    { word: "bronchitis", hint: "This answer has inflamed lungs" },
    { word: "calculator", hint: "This answer might be useful with some hard maths" },
    { word: "capitalism", hint: "Economic and political system based on the motive of profit" },
    { word: "centimetre", hint: "One hundreth of a metre" },
    { word: "cheesecake", hint: "Creamy desert with a variation symbolic with New York" },
    { word: "childbirth", hint: "This answer is going into labour" },
    { word: "collateral", hint: "1 bullet 2 kills" },
    { word: "cappuccino", hint: "Espresso, steamed milk and milk foam in even distributions" },
    { word: "childbirth", hint: "Species of great ape native to tropical Africa" },
    { word: "chopsticks", hint: "Eating utensils used especially by the Chinese and Japanese" },
    { word: "cloudburst", hint: "Extreme rain in a very short amount of time" },
    { word: "collection", hint: "This answer is a group of things" },
    { word: "comestible", hint: "This answer describes an something which can be eaten, similar to edible" },
    { word: "commercial", hint: "This answer intends to make a profit" },
    { word: "commission", hint: "A car salesman might get this answer for each time they sell a car" },
    { word: "commitment", hint: "This answer is sure to not give up" },
    { word: "comparison", hint: "This answer is concerned with similarities and differences" },
    { word: "compassion", hint: "This answer is concerned about the wellbeing of others" },
    { word: "competence", hint: "The ability to do something successfully or effectively" },
    { word: "competitor", hint: "This answer is trying to sell a similar product to the same people" },
    { word: "completion", hint: "All finished" },
    { word: "complexity", hint: "This answer is complicated" },
    { word: "compliance", hint: "Obeying an order or accepting a wish or command" },
    { word: "compliment", hint: "You're looking good today" },
    { word: "compromise", hint: "This answer settles a dispute but at a cost" },
    { word: "compulsion", hint: "This answer can't control themselves" },
    { word: "conception", hint: "The egg is fertilised and gives rise to offspring" },
    { word: "conclusion", hint: "This answer is the last part" },
    { word: "conference", hint: "A large, formal meeting" },
    { word: "confidence", hint: "This answer believes in themself" },
    { word: "conscience", hint: "This answer senses what is right or wrong" },
    { word: "conspiracy", hint: "This answer is secretly plotting something" },
    { word: "consulting", hint: "This answer provides advice or expertise" },
    { word: "continuity", hint: "This answer is making sure things are consistent from scene to scene" },
    { word: "contractor", hint: "This answer normally comes with a games console" },
    { word: "consulting", hint: "The process of heat transfer through heated fluids (most commonly air or water)" },
    { word: "convention", hint: "E3" },
    { word: "conversion", hint: "Kilometres --> Miles, Celsius --> Fahrenheit" },
    { word: "conviction", hint: "A judge is to deem this answer guilty of a criminal offence" },
    { word: "cornflakes", hint: "A breakfast cereal made from corn" },
    { word: "corruption", hint: "This answer is stealing money as a goverment official" },
    { word: "counsellor", hint: "This answer might speak to and help someone with their marriage problems" },
    { word: "courthouse", hint: "The building where a judge delivers sentences to criminals" },
    { word: "creativity", hint: "This answer is thinking outside the box" },
    { word: "consulting", hint: "This answer is one of a group of people on a ship" },
    { word: "cultivator", hint: "Farming equipment that stirs the soil" },
    { word: "curriculum", hint: "This answer describes everything a student will learn through their education" },
    { word: "decoration", hint: "Making your home look a bit nicer" },
    { word: "decryption", hint: "Ciphertext --> Plaintext" },
    { word: "encryption", hint: "Plaintext --> Ciphertext" },
    { word: "dedication", hint: "This answer is committed and will never give up" },
    { word: "decryption", hint: "This answer explains what a word means" },
    { word: "department", hint: "The different areas of a large store" },
    { word: "deployment", hint: "This answer is being sent to a place of war" },
    { word: "decryption", hint: "This answer is feeling very low" },
    { word: "descendant", hint: "This answer is offspring of a specific ancestor" },
    { word: "dictionary", hint: "A-Z" },
    { word: "difficulty", hint: "Easy, Normal, Hard" },
    { word: "disclaimer", hint: "This answer is not responsible for any damage caused" },
    { word: "discretion", hint: "The freedom to decide what should be done in a particular situation" },
    { word: "dishwasher", hint: "This answer cleans plates and cutlery" },
    
  ];

  export const words_ten = [
    "discussion",
    "disruption",
    "dissonance",
    "distortion",
    "domination",
    "downstairs",
    "dramaturge",
    "drawbridge",
    "dumbwaiter",
    "earthquake",
    "ectodermal",
    "effacement",
    "efficiency",
    "eicosanoid",
    "elderberry",
    "elongation",
    "employment",
    "engagement",
    "enrollment",
    "enterprise",
    "enthusiasm",
    "epithelium",
    "equivalent",
    "espadrille",
    "evaluation",
    "everything",
    "excellence",
    "excitement",
    "exhaustion",
    "exhibition",
    "expectancy",
    "expedition",
    "experience",
    "experiment",
    "exposition",
    "expression",
    "extinction",
    "eyeglasses",
    "fahrenheit",
    "federation",
    "fertilizer",
    "fiberglass",
    "fibroblast",
    "fingerling",
    "fingernail",
    "fishmonger",
    "floodplain",
    "flugelhorn",
    "foodstuffs",
    "foundation",
    "fratricide",
    "friendship",
    "gastronomy",
    "generation",
    "generosity",
    "girlfriend",
    "governance",
    "government",
    "graduation",
    "grandchild",
    "grapefruit",
    "greenhouse",
    "gymnastics",
    "handmaiden",
    "headphones",
    "hearthside",
    "helicopter",
    "hemisphere",
    "hesitation",
    "hippodrome",
    "homogenate",
    "homosexual",
    "hovercraft",
    "hydraulics",
    "hydrolysis",
    "hypothesis",
    "icebreaker",
    "illiteracy",
    "impairment",
    "impediment",
    "importance",
    "impression",
    "incubation",
    "indication",
    "individual",
    "inequality",
    "inevitable",
    "infarction",
    "ingredient",
    "inhabitant",
    "inhibition",
    "initialise",
    "initialize",
    "initiative",
    "injunction",
    "innovation",
    "inspection",
    "instructor",
    "instrument",
    "insulation",
    "insurgence",
    "interloper",
    "intervenor",
    "investment",
    "invitation",
    "irrigation",
    "jellybeans",
    "journalism",
    "journalist",
    "juggernaut",
    "kettledrum",
    "laboratory",
    "laryngitis",
    "leadership",
    "legislator",
    "legitimacy",
    "lieutenant",
    "likelihood",
    "limitation",
    "literature",
    "litigation",
    "littleneck",
    "locomotive",
    "loneliness",
    "lymphocyte",
    "macrofauna",
    "mainstream",
    "maintainer",
    "management",
    "manservant",
    "matchmaker",
    "mayonnaise",
    "medication",
    "membership",
    "mesenchyme",
    "metabolite",
    "microphone",
    "millennium",
    "millimeter",
    "minimalism",
    "misreading",
    "missionary",
    "monitoring",
    "monotheism",
    "morphology",
    "motivation",
    "motorcycle",
    "mozzarella",
    "multimedia",
    "mycoplasma",
    "navigation",
    "networking",
    "newsletter",
    "nightlight",
    "nucleotide",
    "obligation",
    "occupation",
    "occurrence",
    "opposition",
    "ordination",
    "organising",
    "organizing",
    "outfielder",
    "overcharge",
    "overflight",
    "overweight",
    "paramecium",
    "parliament",
    "particular",
    "patrolling",
    "penicillin",
    "percentage",
    "perception",
    "perfection",
    "periodical",
    "peripheral",
    "permafrost",
    "permission",
    "petitioner",
    "pharmacist",
    "phenomenon",
    "philosophy",
    "photodiode",
    "photograph",
    "physiology",
    "pilgrimage",
    "plagiarism",
    "plantation",
    "playground",
    "playwright",
    "pocketbook",
    "politician",
    "popularity",
    "population",
    "possession",
    "precedence",
    "preference",
    "presidency",
    "prevalence",
    "prevention",
    "priesthood",
    "prizefight",
    "processing",
    "production",
    "profession",
    "progenitor",
    "propaganda",
    "proportion",
    "proprietor",
    "prosecutor",
    "prosperity",
    "prostanoid",
    "protection",
    "providence",
    "pseudocode",
    "psychology",
    "publishing",
    "punishment",
    "questioner",
    "radiosonde",
    "recreation",
    "referendum",
    "reflection",
    "regulation",
    "relaxation",
    "reluctance",
    "reparation",
    "repository",
    "republican",
    "reputation",
    "researcher",
    "resistance",
    "resolution",
    "restaurant",
    "rethinking",
    "retirement",
    "retouching",
    "retrospect",
    "revelation",
    "revolution",
    "rheumatism",
    "rhinoceros",
    "roundabout",
    "sauerkraut",
    "scheduling",
    "sculptural",
    "semicircle",
    "sentencing",
    "separation",
    "settlement",
    "shirtdress",
    "shoestring",
    "sidestream",
    "similarity",
    "simplicity",
    "skyscraper",
    "sleepiness",
    "solidarity",
    "somersault",
    "sousaphone",
    "specialist",
    "spectacles",
    "spiderling",
    "standpoint",
    "statistics",
    "stepmother",
    "storyboard",
    "strawberry",
    "subroutine",
    "subsection",
    "subsidence",
    "subsidiary",
    "suggestion",
    "sunglasses",
    "supervisor",
    "supplement",
    "suspenders",
    "suspension",
    "sustenance",
    "sweatshirt",
    "swordfight",
    "tabernacle",
    "tablecloth",
    "tachometer",
    "tambourine",
    "technician",
    "technology",
    "telescreen",
    "television",
    "temptation",
    "terracotta",
    "thermostat",
    "tomography",
    "toothbrush",
    "toothpaste",
    "tortellini",
    "tournament",
    "trafficker",
    "transcript",
    "transition",
    "typewriter",
    "unblinking",
    "underneath",
    "underpants",
    "undershirt",
    "undertaker",
    "uniformity",
    "university",
    "vegetarian",
    "vegetation",
    "vermicelli",
    "vernacular",
    "vibraphone",
    "volatility",
    "volleyball",
    "watchmaker",
    "watercress",
    "waterfront",
    "watermelon",
    "waterspout",
    "waterwheel",
    "weedkiller",
    "wholesaler",
    "wildebeest",
    "wilderness",
    "windscreen",
    "windshield",
    "withdrawal",
    "wraparound",
  ];
  